name: Create envfile

on:
  workflow_dispatch:

jobs:

  create-envfile:
 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
        
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ vars.AWS_REGION }}
        S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}
        directory: env
        fail_on_empty: false
        sort_keys: false
        
    - name: Debug - List Files
      run: ls -la

    - name: Upload .env File as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: .env
        path: .env
