name: Setup for Local Development

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    defaults:
     run:
       working-directory: ./env
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create .env File
        run: |
          touch .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "AWS_REGION=${{ vars.AWS_REGION }}" >> .env
          echo "S3_BUCKET_NAME=${{ vars.IMG_BUCKET }}" >> .env
          cat .env
      - name: Current Directory
        run: pwd
      - name: Debug - List Files
        run: ls -la

      - name: Upload .env File as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: .env
          path: env/.env
          if-no-files-found: error
